package swing;

import java.util.ArrayList;
import java.util.List;

public class FM_Barang extends javax.swing.JDialog {
    List<barang_class> daftarbarang = new ArrayList<>();

    public FM_Barang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        initstatic();
        
    daftarbarang.add(new barang_class("001","HDD",500000));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtkode = new javax.swing.JTextField();
        jtnama = new javax.swing.JTextField();
        jtharga = new javax.swing.JTextField();
        jbtambah = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbtutup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtcari = new javax.swing.JTextField();
        jbcari = new javax.swing.JButton();
        jbreload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });

        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });

        jbupdate.setText("Edit");

        jbhapus.setText("Hapus");

        jbtutup.setText("Tutup");
        jbtutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtutupActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Harga");

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelbarang);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 3, 24)); // NOI18N
        jLabel4.setText("BARANG");

        jbcari.setText("Cari");

        jbreload.setText("Reload");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtkode)
                                    .addComponent(jtnama)
                                    .addComponent(jtharga)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtambah)
                                .addGap(18, 18, 18)
                                .addComponent(jbsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(jbupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jbhapus)
                                .addGap(18, 18, 18)
                                .addComponent(jbtutup))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbcari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbreload)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtambah)
                    .addComponent(jbsimpan)
                    .addComponent(jbupdate)
                    .addComponent(jbhapus)
                    .addComponent(jbtutup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcari)
                    .addComponent(jbreload))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
    addstate();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbtutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtutupActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtutupActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        barang_class barang = new barang_class();
        barang.setKode(jtkode.getText());
        barang.setNama(jtnama.getText());
        barang.setHarga(new Integer(jtharga.getText()));
            daftarbarang.add(barang);
        initstatic();
    }//GEN-LAST:event_jbsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbcari;
    private javax.swing.JButton jbhapus;
    private javax.swing.JButton jbreload;
    private javax.swing.JButton jbsimpan;
    private javax.swing.JButton jbtambah;
    private javax.swing.JButton jbtutup;
    private javax.swing.JButton jbupdate;
    private javax.swing.JTextField jtcari;
    private javax.swing.JTextField jtharga;
    private javax.swing.JTextField jtkode;
    private javax.swing.JTextField jtnama;
    private javax.swing.JTable tabelbarang;
    // End of variables declaration//GEN-END:variables
   
    private void initstatic() {
        jtkode.setEnabled(false);
        jtnama.setEnabled(false);
        jtharga.setEnabled(false);
        jtcari.setEnabled(false);
        jbsimpan.setEnabled(false);
        jbhapus.setEnabled(false);
        jbupdate.setEnabled(false);
        jbcari.setEnabled(false);
        jbreload.setEnabled(false);
        //tampilkan data tabel
        tabelbarang.setModel(new Barang_Table(daftarbarang));
        jbtambah.setEnabled(true);
//To change body of generated methods, choose Tools | Templates.
    }
private void addstate(){
        jtkode.setEnabled(true);
        jtnama.setEnabled(true);
        jtharga.setEnabled(true);
        jtkode.requestFocus();
        //aktif simpan button
        jbsimpan.setEnabled(true);
        jbtambah.setEnabled(false);
}
}
