/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import javax.swing.JMenuItem;

/**
 *
 * @author Eralab
 */
public class Menu_Utama extends javax.swing.JFrame {
    static boolean loggedin=false;

    public static boolean isLoggedin() {
        return loggedin;
    }

    public static void setLoggedin(boolean loggedin) {
        Menu_Utama.loggedin = loggedin;
    }
    

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
        setExtendedState(Menu_Utama.MAXIMIZED_BOTH);
        initstatic(loggedin);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menufile = new javax.swing.JMenu();
        jlogin = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jexit = new javax.swing.JMenuItem();
        Menumaster = new javax.swing.JMenu();
        jbarang = new javax.swing.JMenuItem();
        jsupplier = new javax.swing.JMenuItem();
        jpelanggan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jakun = new javax.swing.JMenuItem();
        Menutransaksi = new javax.swing.JMenu();
        jpembelian = new javax.swing.JMenuItem();
        jpenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 255, 255));

        Menufile.setText("File");

        jlogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        Menufile.add(jlogin);

        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        Menufile.add(jlogout);
        Menufile.add(jSeparator1);

        jexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        Menufile.add(jexit);

        jMenuBar1.add(Menufile);

        Menumaster.setText("Master");

        jbarang.setText("Barang");
        jbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarangActionPerformed(evt);
            }
        });
        Menumaster.add(jbarang);

        jsupplier.setText("Supplier");
        jsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupplierActionPerformed(evt);
            }
        });
        Menumaster.add(jsupplier);

        jpelanggan.setText("Pelanggan");
        jpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpelangganActionPerformed(evt);
            }
        });
        Menumaster.add(jpelanggan);
        Menumaster.add(jSeparator2);

        jakun.setText("Akun");
        jakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jakunActionPerformed(evt);
            }
        });
        Menumaster.add(jakun);

        jMenuBar1.add(Menumaster);

        Menutransaksi.setText("Transaksi");

        jpembelian.setText("Pembelian");
        Menutransaksi.add(jpembelian);

        jpenjualan.setText("Penjualan");
        Menutransaksi.add(jpenjualan);

        jMenuBar1.add(Menutransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
    loginForm log=new loginForm(this, true);
    log.setVisible(true);
        initstatic(loggedin);
    }//GEN-LAST:event_jloginActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jexitActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarangActionPerformed
    FM_Barang FB = new FM_Barang(this, true);
    FB.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbarangActionPerformed

    private void jsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupplierActionPerformed
    FM_Supplier Sup=new FM_Supplier(this, true);
    Sup.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jsupplierActionPerformed

    private void jpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpelangganActionPerformed
    FM_Pelanggan pel=new FM_Pelanggan(this, true);
    pel.setVisible(true);
    }//GEN-LAST:event_jpelangganActionPerformed

    private void jakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jakunActionPerformed
    FM_Akun akun=new FM_Akun(this, true);
    akun.setVisible(true);
    }//GEN-LAST:event_jakunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menufile;
    private javax.swing.JMenu Menumaster;
    private javax.swing.JMenu Menutransaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jakun;
    private javax.swing.JMenuItem jbarang;
    private javax.swing.JMenuItem jexit;
    private javax.swing.JMenuItem jlogin;
    private javax.swing.JMenuItem jlogout;
    private javax.swing.JMenuItem jpelanggan;
    private javax.swing.JMenuItem jpembelian;
    private javax.swing.JMenuItem jpenjualan;
    private javax.swing.JMenuItem jsupplier;
    // End of variables declaration//GEN-END:variables

    private void initstatic(boolean b) {
       swingutil util = new swingutil();
       util.enableMenus(b, jlogout, jakun, jbarang, jpelanggan,
               jpembelian, jpenjualan, jsupplier);
        
    }

}
class swingutil {
public void enableMenus(boolean active, JMenuItem...items) {
    for (JMenuItem item : items) {
        item.setEnabled(active);
}
}
}